import { BugReport } from "./scanService";

// Export bug reports as JSON
export function exportAsJSON(reports: BugReport[]): void {
  const data = JSON.stringify(reports, null, 2);
  const blob = new Blob([data], { type: "application/json" });
  downloadFile(blob, `bug-reports-${Date.now()}.json`);
}

// Export bug reports as DOC (HTML-based Word document)
export function exportAsDOC(reports: BugReport[]): void {
  const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Bug Reports</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      line-height: 1.6;
      margin: 40px;
      color: #333;
    }
    h1 {
      color: #2563eb;
      border-bottom: 3px solid #2563eb;
      padding-bottom: 10px;
      margin-bottom: 30px;
    }
    .report {
      margin-bottom: 40px;
      page-break-inside: avoid;
    }
    .report-header {
      background-color: #f3f4f6;
      padding: 15px;
      border-left: 4px solid #2563eb;
      margin-bottom: 15px;
    }
    .report-title {
      font-size: 18px;
      font-weight: bold;
      color: #1f2937;
      margin: 0 0 5px 0;
    }
    .report-date {
      font-size: 12px;
      color: #6b7280;
      margin: 0;
    }
    .report-details {
      padding: 15px;
      background-color: #fafafa;
      border-radius: 4px;
      white-space: pre-wrap;
      font-family: 'Courier New', monospace;
      font-size: 14px;
    }
    .summary {
      margin-bottom: 30px;
      padding: 20px;
      background-color: #dbeafe;
      border-radius: 8px;
    }
    .footer {
      margin-top: 50px;
      padding-top: 20px;
      border-top: 2px solid #e5e7eb;
      text-align: center;
      color: #6b7280;
      font-size: 12px;
    }
  </style>
</head>
<body>
  <h1>🐛 Bug Reports - RepoIQ</h1>
  
  <div class="summary">
    <p><strong>Total Reports:</strong> ${reports.length}</p>
    <p><strong>Generated:</strong> ${new Date().toLocaleString()}</p>
  </div>

  ${reports
    .map(
      (report) => `
    <div class="report">
      <div class="report-header">
        <p class="report-title">${escapeHtml(report.title)}</p>
        <p class="report-date">Report ID: #${report.id} | Repository: ${escapeHtml(report.repoName)} | Reported on: ${new Date(report.timestamp).toLocaleString()}</p>
        <p class="report-date">Severity: ${escapeHtml(report.severity || "medium")} | Status: ${escapeHtml(report.status || "open")}</p>
      </div>
      <div class="report-details">${escapeHtml(report.details)}</div>
    </div>
  `
    )
    .join("")}

  <div class="footer">
    <p>Generated by RepoIQ | ${new Date().toLocaleDateString()}</p>
  </div>
</body>
</html>
  `.trim();

  const blob = new Blob(["\ufeff", html], {
    type: "application/msword",
  });
  downloadFile(blob, `bug-reports-${Date.now()}.doc`);
}

// Export bug reports as PDF (using print-friendly HTML)
export function exportAsPDF(reports: BugReport[]): void {
  const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Bug Reports</title>
  <style>
    @media print {
      body { margin: 0; }
    }
    body {
      font-family: Arial, sans-serif;
      line-height: 1.6;
      margin: 20mm;
      color: #000;
    }
    h1 {
      color: #2563eb;
      border-bottom: 3px solid #2563eb;
      padding-bottom: 10px;
      margin-bottom: 20px;
      font-size: 24px;
    }
    .report {
      margin-bottom: 30px;
      page-break-inside: avoid;
      border: 1px solid #ddd;
      padding: 15px;
      border-radius: 4px;
    }
    .report-title {
      font-size: 16px;
      font-weight: bold;
      color: #1f2937;
      margin: 0 0 5px 0;
    }
    .report-date {
      font-size: 11px;
      color: #6b7280;
      margin: 0 0 10px 0;
    }
    .report-details {
      padding: 10px;
      background-color: #f9f9f9;
      border-left: 3px solid #2563eb;
      white-space: pre-wrap;
      font-family: 'Courier New', monospace;
      font-size: 12px;
    }
    .summary {
      margin-bottom: 20px;
      padding: 15px;
      background-color: #f0f9ff;
      border-radius: 4px;
      border-left: 4px solid #2563eb;
    }
    .footer {
      margin-top: 30px;
      padding-top: 15px;
      border-top: 2px solid #e5e7eb;
      text-align: center;
      color: #6b7280;
      font-size: 10px;
    }
  </style>
</head>
<body>
  <h1>🐛 Bug Reports - RepoIQ</h1>
  
  <div class="summary">
    <p><strong>Total Reports:</strong> ${reports.length}</p>
    <p><strong>Generated:</strong> ${new Date().toLocaleString()}</p>
  </div>

  ${reports
    .map(
      (report) => `
    <div class="report">
      <p class="report-title">${escapeHtml(report.title)}</p>
      <p class="report-date">Report ID: #${report.id} | Repository: ${escapeHtml(report.repoName)} | Reported: ${new Date(report.timestamp).toLocaleString()}</p>
      <p class="report-date">Severity: ${escapeHtml(report.severity || "medium")} | Status: ${escapeHtml(report.status || "open")}</p>
      <div class="report-details">${escapeHtml(report.details)}</div>
    </div>
  `
    )
    .join("")}}

  <div class="footer">
    <p>Generated by RepoIQ | ${new Date().toLocaleDateString()}</p>
  </div>
  
  <script>
    window.onload = function() {
      window.print();
      setTimeout(() => window.close(), 100);
    };
  </script>
</body>
</html>
  `.trim();

  // Open in new window and trigger print
  const printWindow = window.open("", "_blank");
  if (printWindow) {
    printWindow.document.write(html);
    printWindow.document.close();
  }
}

// Helper function to escape HTML entities
function escapeHtml(text: string): string {
  const div = document.createElement("div");
  div.textContent = text;
  return div.innerHTML;
}

// Helper function to trigger file download
function downloadFile(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
